routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();


Route::group(['prefix' => App\Http\Middleware\Locale::getLocale()], function() {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('takehelp', 'HomeController@takehelp');
    Route::get('programs', 'HomeController@programs');
    Route::get('thankyou', 'DonationController@thankyou');
    Route::post('donatesuccess/{id}', 'DonationController@donatesuccess');
    Route::get('search', 'SearchController@search');
    Route::get('smshelp', 'HomeController@smshelp');
    Route::get('alreadyhelp', 'AlreadyController@index');
    Route::get('alreadyhelp/{id}/{slag}', 'AlreadyController@show');
    Route::get('children/donate', 'ChildrenController@donate');
    Route::get('children/{id}/{slag}', 'ChildrenController@show');
    Route::get('news', 'NewsController@index');
    Route::get('news/{id}/{slag}', 'NewsController@show');
    Route::get('videos', 'VideosController@index');
    Route::get('promotions', 'StocksController@index');
    Route::get('promotions/{id}/{slag}', 'StocksController@show');
    Route::get('specinfo', 'SpecinfoController@index');
    Route::get('specinfo/{id}/{slag}', 'SpecinfoController@show');
    Route::get('staff', 'StaffController@index');
    Route::get('staff/{id}/{slag}', 'StaffController@show');
    Route::get('donation/{id}', 'DonationController@show');
});


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){
    Route::get('/', ['uses' => 'AdminController@show'])->name('admin_index');
    Route::resource('news','Admin\NewsController', ['except' => ['show']]);
    Route::get('news/port', 'Admin\NewsController@ajax')
        ->name('get.news.data');
    Route::resource('users','Admin\UsersController', ['except' => ['show']]);
    Route::get('users/port', 'Admin\UsersController@ajax')
        ->name('get.users.data');
    Route::resource('pages','Admin\PagesController', ['except' => ['show']]);
    Route::resource('stocks','Admin\StocksController', ['except' => ['show']]);
    Route::get('stocks/port', 'Admin\StocksController@ajax')
        ->name('get.stocks.data');
    Route::resource('staff','Admin\StaffController', ['except' => ['show']]);
    Route::resource('videos','Admin\VideosController', ['except' => ['show']]);
    Route::resource('specinfo','Admin\SpecinfoController', ['except' => ['show']]);
    Route::get('specinfo/port', 'Admin\SpecinfoController@ajax')
        ->name('get.specinfo.data');
    Route::resource('cities','Admin\CitiesController', ['except' => ['show']]);

    Route::post('options/addgroup', 'Admin\OptionsController@addgroup');
    Route::get('currency', 'Admin\OptionsController@currency');
    Route::resource('options','Admin\OptionsController', ['except' => ['show']]);

    Route::resource('sponsors','Admin\SponsorsController', ['except' => ['show']]);
    Route::resource('donate','Admin\DonateController', ['except' => ['show']]);
    Route::resource('children','Admin\ChildrenController', ['except' => ['show']]);
    Route::get('children/port', 'Admin\ChildrenController@ajax')
        ->name('get.children.data');
    Route::get('album/port', 'Admin\AlbumController@ajax')
        ->name('get.album.data');
    Route::get('donate/port', 'Admin\DonateController@ajax')
        ->name('get.donate.data');
    Route::resource('photos','Admin\PhotoController', ['except' => ['show']]);
    Route::resource('album','Admin\AlbumController');

});



Route::get('setlocale/{locale}', function ($locale) {
    if (in_array($locale, \Config::get('app.locales'))) {
        $referer = Redirect::back()->getTargetUrl();
        $parse_url = parse_url($referer, PHP_URL_PATH);
        if ($parse_url == null) $parse_url = '/';
        $segments = explode('/', $parse_url);
        $params = substr(strstr($referer, '?'), 1, strlen($referer));

        if (in_array($segments[1],  Config::get('app.locales'))) {

            unset($segments[1]);
        }
        if ($locale != Config::get('app.locale')){
            if ($locale != 'ru') {  array_splice($segments, 1, 0, $locale); }

        }
        if ($params != '') {
            $url = Request::root().implode("/", $segments).'?'.$params;
        } else{
            $url = Request::root().implode("/", $segments).$params;

        }
    }

    return redirect($url);

})->name('setlocale');

app/Pages.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pages extends Model
{
    protected $table="pages";
    protected $fillable=['type','title_ru','content_ru','title_ua','content_ua','title_en','content_en','title_de','content_de','public','photo_id','user_id'];

    public function getfields() {
        switch ($this->type) {
            case ('takehelp') :
                return
                    [
                        ['title'=> 'Текст перед файлом', 'name'=>'text_before_file','type' =>'textarea'],
                        ['title'=> 'Анкета файл', 'name'=>'file','type' =>'file'],
                        ['title'=> 'Текст после файла', 'name'=>'text_after_file','type' =>'textarea']
                    ]; break;
            case ('team') :
                return
                    [
                        ['title'=> 'Текст', 'name'=>'text','type' =>'textarea'],
                    ]; break;

            case ('programs') :
                return
                    [
                        ['title'=> 'Текст', 'name'=>'text','type' =>'textarea'],
                    ]; break;

            case ('smshelp') :
                return
                    [
                        ['title'=> 'Текст', 'name'=>'text','type' =>'textarea'],
                    ]; break;

        }
    }

    public function photo() {
        return $this->belongsTo('App\Photos', 'photo_id');
    }

    public function getPreviewAttribute(){
//        $photo = $this->hasOne('App\Photos','id','photo_id')->first();
        $photo = $this->photo;
        if ($photo) {
            return $photo->icon_url;
        }
        return '/images/no-image.png';
    }

    public function getImageUrlAttribute(){
        $photo = $this->photo;
        if ($photo) {
            return $photo->url;
        }
        return '/images/no-image.png';
    }



    public function getTitleAttribute(){
        $locale = \App::getLocale();
        $name = 'title_'.$locale;
        return $this->$name;
    }

    public function getContentAttribute(){
        $locale = \App::getLocale();
        $content = 'content_'.$locale;
        $result = $this->$content;
        return json_decode($result);
    }
}

app/Staff.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Event;

class Staff extends Model
{
    protected $table="staff";
    protected $fillable=['preview', 'name_ru','details_ru','position_ru','name_ua','details_ua','position_ua','name_en','details_en','position_en','name_de','details_de','position_de','telephon','email','public','photo_id','user_id','photo'];

    public static function boot()

    {

        parent::boot();

        static::created(function($staff){

            Event::fire('staff.created',$staff);

        });

        static::updated(function($staff){

            Event::fire('staff.updated',$staff);

        });

        static::deleted(function($staff){

            Event::fire('staff.deleted',$staff);

        });

    }

    public function photo() {
        return $this->belongsTo('App\Photos', 'photo_id');
    }

    public function getPreviewAttribute(){
        $photo = $this->photo;
        if ($photo) {
            return $photo->icon_url;
        }
        return '/images/no-image.png';
    }
    public function getShortAttribute() {
        return mb_substr(strip_tags($this->details), 0, 170);
    }
    public function getLinkAttribute(){
        return '/staff/'.$this->id.'/'.$this->slug;
    }
    public function getNameAttribute(){
        $locale = \App::getLocale();
        $name = 'name_'.$locale;
        return $this->$name;
    }
    public function getPositionAttribute(){
        $locale = \App::getLocale();
        $position = 'position_'.$locale;
        return $this->$position;
    }

    public function getDetailsAttribute(){
        $locale = \App::getLocale();
        $details = 'details_'.$locale;
        return $this->$details;
    }

    public function getStaffPreviewAttribute(){
        $photo = $this->photo;
        if ($photo) {
            return $photo->icon_url_staff_preview;
        }
        return '/images/no-image.png';
    }

    public function getStaffInsideAttribute(){
        $photo = $this->photo;
        if ($photo) {
            return $photo->icon_url_staff_inside;
        }
        return '/images/no-image.png';
    }

    public function setPhotoAttribute($value){
        if (isset($value['id']))  {
            $image = Photos::findOrFail($value['photo_id']);
            $image->createPreviewCropIcon('staff_preview',$value['detail_x'],$value['detail_y'],$value['detail_height'],$value['detail_width']);
            $image->createPrewIcon('staff_inside',350,350);
            $this->attributes['photo_id'] = $value['photo_id'];
        } else {
            $this->attributes['preview_id'] = null;
        }
    }

    public function getSlugAttribute(){
        $text = $this->name_ru;

        $trans = [
            'а' => 'a', 'б' => 'b', 'в' => 'v', 'г' => 'g', 'д' => 'd', 'е' => 'e', 'ё' => 'jo', 'ж' => 'zh', 'з' => 'z', 'и' => 'i', 'й' => 'jj',
            'к' => 'k', 'л' => 'l', 'м' => 'm', 'н' => 'n', 'о' => 'o', 'п' => 'p', 'р' => 'r', 'с' => 's', 'т' => 't', 'у' => 'u', 'ф' => 'f',
            'х' => 'kh', 'ц' => 'c', 'ч' => 'ch', 'ш' => 'sh', 'щ' => 'shh', 'ъ' => '', 'ы' => 'y', 'ь' => '', 'э' => 'eh', 'ю' => 'ju', 'я' => 'ja',
        ];
        $text  = mb_strtolower( $text, 'UTF-8' ); // lowercase cyrillic letters too
        $text  = strtr( $text, $trans ); // transliterate cyrillic letters
        $text  = preg_replace( '/[^A-Za-z0-9 _.]/', '', $text );
        $text  = preg_replace( '/[ _.]+/', '-', trim( $text ) );
        $text  = trim( $text, '-' );
        return $text;
    }
}

app/Http/Controllers/Admin/StaffController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Album;
use App\Staff;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class StaffController extends Controller
{
    public function index()
    {
        $staff=Staff::orderBy('id','DESC')->paginate(10);
        return view('admin.staff.index',['staff'=>$staff]);
    }

    public function create()
    {
        $albums = Album::pluck('title','id');
        $locales =  \Config::get('app.locales');

        return view('admin.staff.form',['albums'=>$albums,'locales'=>$locales]);
    }

    public function store(Request $request)
    {
        $data = $request->only('name_ru','details_ru','position_ru','name_ua','details_ua','position_ua','name_en','details_en','position_en','name_de','details_de','position_de','telephon','email','photo','public');
        $data['user_id']=\Auth::id();

        $staff = Staff::create($data);
        return redirect('admin/staff')->with('message','Сотрудник добавлен');
    }

    public function edit($id)
    {
        $record=Staff::findOrFail($id);
        $albums = Album::pluck('title','id');
        $locales =  \Config::get('app.locales');

        return view('admin.staff.form',['record'=>$record,'albums'=>$albums,'locales'=>$locales]);
    }


    public function update(Request $request,$id)
    {
        $staff=Staff::findOrFail($id);
        $data = $request->only('name_ru','details_ru','position_ru','name_ua','details_ua','position_ua','name_en','details_en','position_en','name_de','details_de','position_de','telephon','email','photo','public');
        $staff->update($data);
        return back()->with('message', 'Сотрудник изменен');
    }
    public function destroy($id)
    {
        $staff=Staff::findOrFail($id);
        $staff->delete();
        return redirect('admin/staff')->with('message','Сотрудник удален');
    }
}

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use App\Pages;
use App\Staff;
use Illuminate\Http\Request;

class StaffController extends Controller
{
    public function index()
    {
        $staff=Staff::where([['public','=',1]])->orderBy('id','DESC')->paginate(100);
        $locale = \App::getLocale();
        $page= Pages::where('type', 'team')->firstOrFail();
        $field = $page->content;
        return view('staff.index',['staff'=>$staff,'page'=>$page,'field'=>$field,'locale'=>$locale]);
    }

    public function show($id)
    {
        $staff=Staff::findOrFail($id);
        return view('staff.show',['staff'=>$staff]);
    }
}

resources/views/staff/index.blade.php
@extends('layouts.public')
@section('pageTitle'){{ trans('messages.ourteam') }} @stop

@section('content')
        <div class="breadcrumbs">
            <div><a href="{{(App\Http\Middleware\Locale::getLocale() !='') ? '/':'' }}{{App\Http\Middleware\Locale::getLocale()}}"><i class="fa fa-home" aria-hidden="true"></i>{{ trans('messages.home') }}</a></div>
            <img src="/img/line.png">
            <div><a href="#">{{ trans('messages.ourteam') }}</a></div>
            <img src="/img/line.png">
        </div>
        <div class="main-content">
            <div class="content-item">
                <div class="team-block">
                    @foreach($staff as $member)
                    <a href="{{(App\Http\Middleware\Locale::getLocale() !='') ? '/':'' }}{{App\Http\Middleware\Locale::getLocale()}}{{$member->link}}" class="team-item">
                        <div class="team-item-img">
                            <div class="team-item-img" style="background: url('{{$member->staff_preview}}') no-repeat; background-size: cover;"></div>
                        </div>
                        <div class="team-item-info">
                            <h3>{{$member->name}}</h3>
                            <p>{{$member->position}}</p>
                        </div>
                    </a>
                    @endforeach

                </div>
                <div class="content-item-img">
                    <img src="{{$page->image_url}}">
                </div>
                <div class="content-item-text">
                    <h3>{{$page->title}}</h3>
                    <?php $text='text_'.$locale; ?>
                    {!! $field->$text !!}
                </div>
            </div>
        </div>



@stop

resources/views/staff/show.blade.php
@extends('layouts.public')
@section('pageTitle'){{$staff->name}} @stop

@section('content')

        <div class="breadcrumbs">
            <div><a href="{{(App\Http\Middleware\Locale::getLocale() !='') ? '/':'' }}{{App\Http\Middleware\Locale::getLocale()}}"><i class="fa fa-home" aria-hidden="true"></i>{{ trans('messages.home') }}</a></div>
            <img src="/img/line.png">
            <div><a href="{{(App\Http\Middleware\Locale::getLocale() !='') ? '/':'' }}{{App\Http\Middleware\Locale::getLocale()}}/staff">{{ trans('messages.ourteam') }}</a></div>
            <img src="/img/line.png">
            <div><a href="#">{{$staff->name}}</a></div>
        </div>
        <div class="main-content">
            <div class="content-item">
                <div class="team-details">
                    <div class="team-details-img" style="background: url('{{$staff->staff_inside}}') no-repeat center; background-size: cover;"></div>
                    <div class="team-details-text">
                        <h3>{{$staff->name}}</h3>
                        <p class="">{{$staff->position}}</p>
                        {!! $staff->details !!}
                        <h3>Контакты</h3>
                        <p><a href="tel:{{ $staff->telephon }}">{{ $staff->telephon }}</a> <br>
                        <a href="mailto:{{ $staff->email }}">{{ $staff->email }}</a><br></p>
                    </div>
                </div>
            </div>
        </div>


@stop